const NAC_ROOM_PRICE = 400;
const AC_ROOM_PRICE = 600;
const TRAVEL_COST = 315;
const BREAKFAST_PRICE = 120;
const LUNCH_PRICE = 80;
const DINNER_PRICE = 50;

export default {
  NAC_ROOM_PRICE,
  AC_ROOM_PRICE,
  TRAVEL_COST,
  BREAKFAST_PRICE,
  LUNCH_PRICE,
  DINNER_PRICE
};
