const TYPE_EXPENSE = 'expense';
const TYPE_REFUND = 'refund';

// STATUS
const STATUS_WAITING = 'waiting';
const STATUS_CONFIRMED = 'confirmed';
const STATUS_CANCELLED = 'cancelled';
const STATUS_PENDING = 'pending';
const STATUS_REJECTED = 'rejected';
const STATUS_ACTIVE = 'active';
const STATUS_INACTIVE = 'inactive';
const STATUS_AVAILABLE = 'available';
const STATUS_TAKEN = 'taken';
const STATUS_OPEN = 'open';
const STATUS_CLOSED = 'closed';
const STATUS_ADMIN_CANCELLED = 'admin canceled';
const STATUS_PAYMENT_PENDING = 'payment pending';
const STATUS_CASH_PENDING = 'cash pending';
const STATUS_CASH_COMPLETED = 'cash completed';
const STATUS_PAYMENT_COMPLETED = 'payment completed';
const STATUS_AWAITING_REFUND = 'awaiting refund';
const STATUS_PAYMENT_PARTIAL_COMPLETED = 'partially paid';
const STATUS_ONPREM = 'onprem';
const STATUS_OFFPREM = 'offprem';
const STATUS_RESIDENT = 'PR';
const STATUS_MUMUKSHU = 'MUMUKSHU';
const STATUS_SEVA_KUTIR = 'SEVA KUTIR';
const STATUS_GUEST = 'guest';

// ROOM
const ROOM_DETAIL = 'Room Booking';
const ROOM_WL = 'WL';
const ROOM_STATUS_PENDING_CHECKIN = 'pending checkin';
const ROOM_STATUS_CHECKEDIN = 'checkedin';
const ROOM_STATUS_CHECKEDOUT = 'checkedout';
const ROOM_STATUS_AVAILABLE = 'available';
const ROOM_BLOCKED = 'blocked';

export default {
  TYPE_EXPENSE,
  TYPE_REFUND,
  STATUS_WAITING,
  STATUS_CONFIRMED,
  STATUS_CANCELLED,
  STATUS_PENDING,
  STATUS_REJECTED,
  STATUS_ACTIVE,
  STATUS_INACTIVE,
  STATUS_AVAILABLE,
  STATUS_TAKEN,
  STATUS_OPEN,
  STATUS_CLOSED,
  STATUS_ADMIN_CANCELLED,
  STATUS_PAYMENT_PENDING,
  STATUS_CASH_PENDING,
  STATUS_CASH_COMPLETED,
  STATUS_PAYMENT_COMPLETED,
  STATUS_AWAITING_REFUND,
  STATUS_PAYMENT_PARTIAL_COMPLETED,
  STATUS_ONPREM,
  STATUS_OFFPREM,
  STATUS_RESIDENT,
  STATUS_MUMUKSHU,
  STATUS_SEVA_KUTIR,
  STATUS_GUEST,
  ROOM_DETAIL,
  ROOM_WL,
  ROOM_STATUS_PENDING_CHECKIN,
  ROOM_STATUS_CHECKEDIN,
  ROOM_STATUS_CHECKEDOUT,
  ROOM_STATUS_AVAILABLE,
  ROOM_BLOCKED
};
